//
//  MapstedMap.h
//  map
//
//  Created by Parth Bhatt on 07/03/24.
//  Copyright © 2024 Mapsted. All rights reserved.
//

#import <Foundation/Foundation.h>

//! Project version number for MapstedMap.
FOUNDATION_EXPORT double MapstedMapVersionNumber;

//! Project version string for MapstedMap.
FOUNDATION_EXPORT const unsigned char MapstedMapVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <MapstedMap/PublicHeader.h>

#import <CoreLocation/CoreLocation.h>
#import <zlib.h>

// reduce the compiling error that's autogenerated from -swift.h file
#import <CoreData/CoreData.h>
#import <MessageUI/MessageUI.h>
