//
//  MN-Bridging-Header.h
//  nav
//
//  Created by Tianyun Shan on 2016-11-02.
//  Copyright © 2016 Maspted. All rights reserved.
//

#ifndef MN_Bridging_Header_h
#define MN_Bridging_Header_h

#import <CoreLocation/CoreLocation.h>
#import <zlib.h>

// reduce the compiling error that's autogenerated from -swift.h file
#import <CoreData/CoreData.h>
#import <MessageUI/MessageUI.h>

#endif /* MN_Bridging_Header_h */
